# WLKits-Reforged v0.2.3 配置文件
# 模块对应的相关消息在 message.yml 配置

# 所有的模块配置
modules:
  # [模块] 主插件的相关配置
  main:
    # 是否启用 WLKits 的 debug 调试模式
    # 注意, 开启后服务器后台将会有很多调试信息, 请谨慎开启
    # 默认 false
    debug: false

  # [模块] 防止苦力怕爆炸破坏地形
  anticreeper:
    # 是否启用该模块
    # 默认 true
    enabled: true

    # 是否在控制台显示防止爆炸的提示
    # 默认 false
    notice: false

  # [模块] 附魔书转移
  disenchant:
    # 是否启用该模块
    # 默认 true
    enabled: true

  # [模块] 玩家加入离开服务器信息
  joininfo:
    # 是否启用该模块
    # 如果关闭则会显示原版的加入离开提示
    # 默认 true
    enabled: true

  # [模块] 返回死亡点
  # 和 back 模块功能有相似之处
  backdeath:
    # 是否启用该模块
    # 默认 true
    enabled: true

  # [模块] 返回上一个地点
  back:
    # 是否启用该模块
    # 默认 true
    enabled: true

  # [模块] 家管理
  home:
    # 是否启用该模块
    # 默认 true
    enabled: true

    # 是否在设置家的时候把玩家的朝向等数据同时记录
    # 如果关闭, 传送家的时候只会传送坐标, 不会附带朝向等
    # 默认 false
    set-more: false

  # [模块] 允许玩家自杀
  # 创造等模式无效
  suicide:
    # 是否启用该模块
    # 默认 true
    enabled: true

  # [模块] 跳过夜晚
  skipnight:
    # 是否启用该模块
    # 默认 true
    enabled: true

    # 跳过夜晚需要的睡觉玩家占比
    # 范围为 0~100, 表示 0%~100%
    # 如果为 0 则只要有一名玩家睡觉就会跳过夜晚
    # 默认 100
    percent: 100

  # [模块] 传送请求
  tpa:
    # 是否启用该模块
    # 默认 true
    enabled: true

  # [模块] 地标点
  warp:
    # 是否启用该模块
    # 默认 true
    enabled: true

    # 是否在设置地标点的时候把玩家的朝向等数据同时记录
    # 和 home 的 set-more 一样
    # 默认 false
    set-more: false

    # 是否允许非 OP 设置或删除共用地标点
    # 注意, 开启代表任意玩家都可以设置或删除地标点, 请谨慎开启
    # 默认 false
    allow-public: false

    # 设置或删除共用地标点后是否在全服通知
    # 默认 true
    broadcast: true

  # [模块] 玩家称号
  playertag:
    # 是否启用该模块
    # 默认 true
    enabled: true

    # 称号格式
    # 即在聊天栏, TAB, 计分板上显示的名字
    # 可用占位符: [tag: 称号]
    # 默认 '{tag} '
    format: '{tag} '

  # [模块] 定时公告
  schedulenotice:
    # 是否启用该模块
    # 默认 false
    enabled: false

    # 定时公告的间隔
    # 单位为秒
    # 默认 120 (即 2 分钟)
    interval: 120

  # [模块] 对外开放的 HTTP API
  httpapi:
    # 是否启用该模块
    # 默认 false
    enabled: false

    # API 的端口
    # 默认 25555
    port: 25555

    # 线程池大小
    # 默认 10
    pool: 10

    # 验证时需要的 Token
    # 填空字符串 '' 代表随机生成, 否则代表固定的 Token
    # 默认 ''
    token: ''

  # [模块] 提到玩家高亮
  mention:
    # 是否启用该模块
    # 默认 true
    enabled: true

    # 玩家消息包含的字符, 触发提到玩家
    # 可用占位符: [playerName: 玩家名]
    # 默认 '{playerName}'
    at-player: '{playerName}'

    # 玩家消息包含的字符, 触发提到全体
    # 用空字符串 '' 代表关闭提到全体功能
    # 默认 '@EVERYONE'
    at-all: '@EVERYONE'

    # 显示给玩家的消息效果, 提到玩家
    # 可用占位符: [playerName: 玩家名]
    # 默认 '&a@&2{playerName}'
    at-player-display: '&a@&2{playerName}'

    # 显示给玩家的消息效果, 提到全体
    # 默认 '&a@&2EVERYONE'
    at-all-display: '&b@&3EVERYONE'

    # 是否开启提到全体需要 OP 权限
    # 默认 true
    at-all-need-op: true

    # 是否开启提到玩家给玩家声音提醒
    # 提到全体同时生效
    # 默认 true
    sound-notice: true

  # [模块] WLKits 插件管理
  wlkitscommands:
    # 是否启用该模块
    # 默认 true
    enabled: true

  # [模块] 宏指令
  macro:
    # 是否启用该模块
    # 默认 true
    enabled: true
