# WLKits-Reforged 配置文件

plugins: # 所有的集成小工具
  anticreeper: # 防止苦力怕爆炸破坏地形
    enabled: true
    notice: false # 是否在控制台提示
  disenchant: # 转移附魔到附魔书
    enabled: true
  joininfo: # 显示玩家加入或离开
    enabled: true # 如果关闭则会显示原版加入离开提示
  backdeath: # 返回上一次死亡地点
    enabled: true
  back: # 返回上一个地点
    enabled: true
  home: # 家
    enabled: true
    set-more: false # 设置家的时候把玩家的 yaw, pitch (朝向) 同时记录
  suicide: # 自杀
    enabled: true
    use-vanilla: false # 如果开启则会显示玩家掉出世界或玩家死亡, 而不是显示插件自定义死亡信息
  skipnight: # 跳过夜晚
    enabled: true
    percent: 100 # 跳过夜晚需要的睡觉玩家的占比 (范围 0~100, 表示 0%~100%), 如果为 0 则只要有一名玩家睡觉则会跳过夜晚
  tpa: # 传送
    enabled: true
  warp: # 地标点
    enabled: true
    set-more: false # 设置地标点的时候把玩家的 yaw, pitch (朝向) 同时记录
    allow-public: false # 是否允许非管理员设置或删除公用地标点
    broadcast: true # 设置或删除公用地标点后是否在全服广播
  playertag: # 玩家称号
    enabled: true
    format: '{tag} ' # 称号格式, 例 '[OP] Steve'
  schedulenotice: # 定时公告 公告请配置 message.yml
    enabled: false
    interval: 120 # 定时公告的间隔 (单位: 秒)
