# WLKits-Reforged 配置文件

modules: # 所有的模块
  main: # WLKits
    debug: false # 启用 WLKits 的 debug 模式
  anticreeper: # 防止苦力怕爆炸破坏地形
    enabled: true
    notice: false # 是否在控制台提示
  disenchant: # 转移附魔到附魔书
    enabled: true
  joininfo: # 显示玩家加入或离开
    enabled: true # 如果关闭则会显示原版加入离开提示
  backdeath: # 返回上一次死亡地点
    enabled: true
  back: # 返回上一个地点
    enabled: true
  home: # 家
    enabled: true
    set-more: false # 设置家的时候把玩家的 yaw, pitch (朝向) 同时记录
  suicide: # 自杀
    enabled: true
    use-vanilla: false # 如果开启则会显示玩家掉出世界或玩家死亡, 而不是显示插件自定义死亡信息
  skipnight: # 跳过夜晚
    enabled: true
    percent: 100 # 跳过夜晚需要的睡觉玩家的占比 (范围 0~100, 表示 0%~100%), 如果为 0 则只要有一名玩家睡觉则会跳过夜晚
  tpa: # 传送
    enabled: true
  warp: # 地标点
    enabled: true
    set-more: false # 设置地标点的时候把玩家的 yaw, pitch (朝向) 同时记录
    allow-public: false # 是否允许非管理员设置或删除公用地标点
    broadcast: true # 设置或删除公用地标点后是否在全服广播
  playertag: # 玩家称号
    enabled: true
    format: '{tag} ' # 称号格式, 例 '[OP] Steve'
  schedulenotice: # 定时公告 公告请配置 message.yml
    enabled: false
    interval: 120 # 定时公告的间隔 (单位: 秒)
  httpapi: # HTTP API
    enabled: false
    port: 8080 # 端口
    pool: 10 # 线程池
    token: '' # 固定 Token, 填空代表随机生成

  # [模块] 提到玩家高亮
  mention:
    # 是否开启该模块
    # 默认 true
    enabled: true

    # 玩家消息包含的字符, 触发提到玩家
    # 可用占位符: [playerName: 玩家名]
    # 默认 '{playerName}'
    at-player: '{playerName}'

    # 玩家消息包含的字符, 触发提到全体
    # 用空字符串 '' 代表关闭提到全体功能
    # 默认 '@EVERYONE'
    at-all: '@EVERYONE'

    # 显示给玩家的消息效果, 提到玩家
    # 可用占位符: [playerName: 玩家名]
    # 默认 '&a@&2{playerName}'
    at-player-display: '&a@&2{playerName}'

    # 显示给玩家的消息效果, 提到全体
    # 默认 '&a@&2EVERYONE'
    at-all-display: '&b@&3EVERYONE'

    # 是否开启提到全体需要 OP 权限
    # 默认 true
    at-all-need-op: true

    # 是否开启提到玩家给玩家声音提醒
    # 提到全体同时生效
    # 默认 true
    sound-notice: true
  wlkitscommands: # WLKits 命令集合
    enabled: true
  macro: # 宏指令
    enabled: true
