name: WLKitsReforged
version: '${project.version}'
main: ml.windleaf.wlkitsreforged.core.WLKits
load: STARTUP
authors: [ WindLeaf_qwq, kuaizi, Nzzz964 ]
description: A well-built modular essential plugin for Minecraft 1.12.x-1.18.x Paper/Spigot server
website: https://windleaf.ml/

commands:
  backdeath:
    aliases: [ backd, bd ]
    description: Back to last death location
    permission: wlkits.cmd.backdeath
  back:
    description: Back to last location
    permission: wlkits.cmd.back
  sethome:
    description: Set location as home
    permission: wlkits.cmd.home
  home:
    description: Back to home
    permission: wlkits.cmd.home
  delhome:
    description: Delete home location
    permission: wlkits.cmd.home
  suicide:
    description: Kill yourself
    permission: wlkits.cmd.suicide
  tpa:
    description: Send teleport request
    permission: wlkits.cmd.tpa
  tpaccept:
    aliases: [ tpac ]
    description: Accept the teleport request
    permission: wlkits.cmd.tpa
  tpadeny:
    aliases: [ tpad ]
    description: Deny the teleport request
    permission: wlkits.cmd.tpa
  tpacancel:
    description: Cancel the teleport request
    permission: wlkits.cmd.tpa
  tpahelp:
    description: Show the help of tpa module
    permission: wlkits.cmd.tpa
  setwarp:
    description: Set warp
    permission: wlkits.cmd.warp
  warp:
    description: Teleport to warp
    permission: wlkits.cmd.warp
  delwarp:
    description: Delete the warp
    permission: wlkits.cmd.warp
  warphelp:
    description: Show the help of warp module
    permission: wlkits.cmd.warp
  warplist:
    description: Show all warps
    permission: wlkits.cmd.warplist
  playertag:
    aliases: [ ptag ]
    description: Manage player tag
    permission: wlkits.cmd.playertag
  wlkits:
    description: WLKits plugin commands
    permission: wlkits.cmd.wlkits

permissions:
  wlkits.*:
    description: 'The global permission of WLKits plugin'
    default: op
    children:
      - wlkits.cmd.*
      - wlkits.action.*

  wlkits.cmd.*:
    description: 'The global command permission of WLKits plugin'
    default: op
    children:
      - wlkits.cmd.backdeath
      - wlkits.cmd.back
      - wlkits.cmd.home
      - wlkits.cmd.suicide
      - wlkits.cmd.tpa
      - wlkits.cmd.warp
      - wlkits.cmd.warplist
      - wlkits.cmd.playertag
      - wlkits.cmd.wlkits

  wlkits.cmd.backdeath:
    default: true

  wlkits.cmd.back:
    default: true

  wlkits.cmd.home:
    default: true

  wlkits.cmd.suicide:
    default: true

  wlkits.cmd.tpa:
    default: true

  wlkits.cmd.warp:
    default: true

  wlkits.cmd.warplist:
    default: op

  wlkits.cmd.playertag:
    default: op

  wlkits.cmd.wlkits:
    default: op

  wlkits.action.*:
    description: 'The global action permission of WLKits plugin'
    default: op
    children:
      - wlkits.action.disenchant
      - wlkits.action.skipnight
      - wlkits.action.suicide

  wlkits.action.disenchant:
    default: true

  wlkits.action.skipnight:
    default: true

  wlkits.action.suicide:
    default: true
